# action.yml
name: 'Spring Application Advisor'
description: 'Incrementally upgrade your Spring application dependencies'
branding:
  icon: user-check
  color: green
inputs:
  artifactory_token:
    description: 'Token for Spring Enterprise Subscription'
    required: true
  app_advisor_server:
    description: 'URL endpoint for Spring Application Advisor'
    required: true
  git_token:
    description: 'Authentication token for generating pull requests against repo'
    required: true
  email:
    description: 'Email Address for Spring Enterprise Repo'
    required: true
  build_tool:
    description: 'Selects the build tool used to compile the sources, options: mvnw, mvn, gradlew, gradle (default: mvnw)'
    required: false
    default: mvnw
  saa_version:
    description: 'Spring App Advisor CLI Version'
    required: true
    default: 1.1.3

runs:
  using: 'composite'
  steps:
    - name: Setup Spring Repo
      run: ${{ github.action_path }}/setup-spring-ent-repo.sh
      shell: bash
      env:
        ARTIFACTORY_TOKEN: ${{ inputs.artifactory_token }}
        EMAIL: ${{ inputs.email }}
    - name: Run App Advisor
      run: ${{ github.action_path }}/app-advisor.sh
      shell: bash
      env:
        ARTIFACTORY_TOKEN: ${{ inputs.artifactory_token }}
        APP_ADVISOR_SERVER: ${{ inputs.app_advisor_server }}
        GIT_TOKEN_FOR_PRS: ${{ inputs.git_token }}
        BUILD_TOOL: ${{ inputs.build_tool }}
        VERSION: ${{ inputs.saa_version }}
